name: moniepoint_test
description: "Monie Point Flutter Developer Test"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated: ^2.0.0
  animations: ^2.0.10
  flutter_screenutil: ^5.9.0
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  get: ^4.6.6
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/move_icon.png"
  min_sdk_android: 21 
 
  


flutter:


  uses-material-design: true

 
  assets:
    - assets/pngs/


